SELECT TO_DATE(:1,'YYYY-MM-DD')+ROWNUM-1 WEEKDATE 
 , TO_CHAR((TO_DATE(:1,'YYYY-MM-DD')+ROWNUM-1),'DAY') DAY 
 , TO_CHAR((TO_DATE(:1,'YYYY-MM-DD')+ROWNUM),'D') WEEK_DAY 
 , CASE WHEN (CAST(TO_CHAR(TO_DATE(:1,'YYYY-MM-DD'),'D') AS INTEGER) + ROWNUM) <= :2 THEN LPAD((CAST(TO_CHAR(TO_DATE(:1,'YYYY-MM-DD'),'D') AS INTEGER) + ROWNUM),2,'0') 
   ELSE LPAD(CAST(TO_CHAR((TO_DATE(:1,'YYYY-MM-DD')+ROWNUM),'D') AS INTEGER),2,'0') END WSDAY 
  FROM ALL_OBJECTS
WHERE (TO_DATE(TO_CHAR(TO_DATE(:1,'YYYY-MM-DD'),'YYYY-MM-DD'),'YYYY-MM-DD'))+ROWNUM-1 BETWEEN TO_DATE(:1,'YYYY-MM-DD') AND TO_DATE(:1,'YYYY-MM-DD')+13  
